save_dir: /home/newin/Projects/nanodet_sign/workspace/traffic_sign

# ================= MODEL =================
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998

  arch:
    name: NanoDetPlus
    detach_epoch: 10

    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2, 3, 4]
      activation: LeakyReLU

    fpn:
      name: GhostPAN
      in_channels: [116, 232, 464]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: true
      activation: LeakyReLU

    head:
      name: NanoDetPlusHead
      num_classes: 21
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: true
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

    aux_head:
      name: SimpleConvHead
      num_classes: 21
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7

# ================= DATA =================
data:
  train:
    name: CocoDataset
    img_path: /home/newin/Projects/nanodet_sign/Nano_sign/yolodark_nano_dataset/train/images
    ann_path: /home/newin/Projects/nanodet_sign/Nano_sign/coco_annotation/instances_train.json
    input_size: [416, 416]
    keep_ratio: false
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize:
        - [103.53, 116.28, 123.675]
        - [57.375, 57.12, 58.395]

  val:
    name: CocoDataset
    img_path: /home/newin/Projects/nanodet_sign/Nano_sign/yolodark_nano_dataset/valid/images
    ann_path: /home/newin/Projects/nanodet_sign/Nano_sign/coco_annotation/instances_valid.json
    input_size: [416, 416]
    keep_ratio: false
    pipeline:
      normalize:
        - [103.53, 116.28, 123.675]
        - [57.375, 57.12, 58.395]

# ================= DEVICE =================
device:
  gpu_ids: [0]
  batchsize_per_gpu: 8     # start with 8
  workers_per_gpu: 6
  precision: 32



# ================= TRAINING =================
schedule:
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05

  warmup:
    name: linear
    steps: 500
    ratio: 0.0001

  lr_schedule:
    name: CosineAnnealingLR
    T_max: 50
    eta_min: 0.00005

  total_epochs: 150
  val_intervals: 10

grad_clip: 35

# ================= EVALUATOR =================
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP


# ================= LOG =================
log:
  interval: 50

# ================= CLASSES =================
class_names:
  - Keep left
  - Keep right
  - No U-turn
  - No left turn
  - No parking
  - No right turn
  - No stopping
  - Parking
  - Pedestrian Crossing
  - Speed Limit -100-
  - Speed Limit -30-
  - Speed Limit -60-
  - Stop Sign
  - Traffic Light -Green-
  - Traffic Light -Red-
  - Traffic Light -Yellow-
  - U-turn
  - bike
  - motobike
  - person
  - vehicle
